version: '3.7'

services:

  mysqld:
    image: mysql:8.0
    volumes:
       - ./mysqldata:/var/lib/mysql
    deploy:
      endpoint_mode: "dnsrr"
    env_file:
      - ./config/mysql.env
    networks:
      - lockdown
    user: "1000"
    restart: on-failure

  neo4j:
    image: neo4j:3.5.0
    deploy:
      endpoint_mode: "dnsrr"
    volumes:
      - ./neo4jdata:/data
    env_file:
      - ./config/neo4j.env
    networks:
      - lockdown
    user: "1000"
    restart: on-failure

networks:
  lockdown:
    name: opensentry_lockdown
    internal: true
