
version: '3.7'

services:

  certificates:
    image: charmixer/self-signed-certificate-creator:0.0.0
    volumes:
      - ./config/certs.json:/conf.json
      - ./certs:/certs
    user: "1000"
    restart: "no"

  hydra-migrate:
    image: oryd/hydra:v1.0.9
    command:
      migrate sql -e --yes --config /hydra.yml
    networks:
      - trusted
    volumes:
      - ./config/hydra.yml:/hydra.yml
    user: "1000"
    restart: "no"

  idp-migrate:
    image: charmixer/idp:0.0.0
    command:
      --migrate
    networks:
      - trusted
    environment:
      - CONFIG_DISCOVERY_PATH=/discovery.yml
      - CONFIG_APP_PATH=/app.yml
    volumes:
      - ./config/discovery.yml:/discovery.yml
      - ./config/idp.yml:/app.yml
    depends_on:
      - hydra-migrate
    user: "1000"
    restart: "no"

  aap-migrate:
    image: charmixer/aap:0.0.0
    command:
      --migrate
    networks:
      - trusted
    environment:
      - CONFIG_DISCOVERY_PATH=/discovery.yml
      - CONFIG_APP_PATH=/app.yml
    volumes:
      - ./config/discovery.yml:/discovery.yml
      - ./config/aap.yml:/app.yml
    depends_on:
      - idp-migrate
    user: "1000"
    restart: "no"

networks:
  trusted:
    name: trusted
