version: '3.7'

services:

  aap-migrate:
    image: charmixer/aap:0.0.0
    command:
      --migrate
    networks:
      - lockdown
    environment:
      - CONFIG_DISCOVERY_PATH=/discovery.yml
      - CONFIG_APP_PATH=/app.yml
    volumes:
      - ../config/discovery.yml:/discovery.yml
      - ../config/aap.yml:/app.yml
    user: "1000"
    restart: "no"

networks:
  lockdown:
    name: opensentry_lockdown
